const Map<String, String> enUS = {
  'phone': 'Enter phone number',
  'login': 'Login',
  'platform':'Advertisers platform',
  'forgetPassword':'Forget password',
  'newAccount':'Register',
  'or':'Or',
  'send':'Send',
  'enterPassword':'Enter password',
  'verifyPhone':'Verify your phone number',
  'pleaseEnterCode':'Please enter code that send  \n on this number',
  'changePhone':'Change phone ?',
  'verify':'Verify',
  'codeNotSend':'Code not send ? resend code',
  'register':'Register',
  'client':'Client',
  'company':'Company',
  'advertiser':'Advertiser',
  'name':'Name',
  'type':'Type',
  'accountName':'Account name',
  'email':'Email',
  'nationalId':'National ID',
  'verifyAndFollow':'Verify and follow',
  'person':'Personal',
'companyName':'Company name',
'accountAdminName':'Account admin name',
'recordNumber':'Trade record number',
  'cian':'Company',
  'requestAdvertise':'Request ad',
  'ads':'Ads',
  'advertisers':'Advertisers',
  'coupons':'Coupons',
  'advertisingData':'Advertising data',
  'productType':'Product type',
  'adType':'Ad type',
  'adDescription':'Ad description : ',
  'adDate':'Ad date',
  'adChannels':'Ad channels',
  'attachments':'Attachments',
  'links':'Links',
  'adTitle':'Ad title',
  'addCoupon':'Add coupon',
  'noticeable':'Noticeable',
  'advertisinPlan':'Advertising plan',
  'findAdvertiser':'Find an advertiser',
  'chooseChannel':'Choose a channel',
  'save':'Save',
  'cancel':'Cancel',
  'attachmentName':'Attachment name',
  'copyCode':'Copy code',
  'urlName':'Url name',
  'urlTitel':'Url title',
  'adPlan':'Ad plan',
  'discountCoupon':'Discount coupon',
  'edit':'Edit'
};